---
abstract: 'Reply with a simple response of just the current time'
author:
  - 'Stefan Adams <sadams@cpan.org>'
build_requires: {}
configure_requires: {}
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.34, CPAN::Meta::Converter version 2.150005'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojolicious-Plugin-ReplyTime
no_index:
  directory:
    - t
    - inc
requires:
  Mojolicious: '7.60'
  perl: '5.008007'
resources:
  MailingList: http://groups.google.com/group/mojolicious
  bugtracker: http://github.com/stefanadams/Mojolicious-Plugin-ReplyTime/issues
  homepage: http://stefan.adams.fm
  license: http://dev.perl.org/licenses/
  repository: http://github.com/stefanadams/Mojolicious-Plugin-ReplyTime
version: '0.7'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
